const STOCKS_ADD = 'ADD_STOCKS'
const STOCKS_DELETE = 'DELETE_STOCKS'
const STOCKS_UPDATE = 'UPDATE_STOCKS'
const STOCKS_INIT = 'INIT_STOCK_TABLE'



export {
  STOCKS_ADD,
  STOCKS_DELETE,
  STOCKS_UPDATE,
  STOCKS_INIT,
}